chore: fix token-meta tests+clean up code (#881)
* auction: fix test build errors

* chore: documenting puff data fields reasoning

* utils: exposing puffed_out_string method

* test: fix create_metadata_account success

- expecting name, symbol and uri to be puffed out

* utils: using puffed_out_string for puff_out_data_fields

* test: wrapping in mods named after file

- supports running test files in isolation, i.e.
  `cargo test-bpf update_primary_sale_happened_via_token`
- improves out put of tests failing vs. passing, i.e.
  `'update_primary_sale_happened_via_token::success' panicked at ..`

* test: fixing update* tests expecting puffed strings

* chore: adding note to mint tests about token-vault dependency

* chore: adding rust format

- adapted to current formatting especially line width
- enforcing ordering and grouping of imports since at this point they
  are all over the place
- the exact specs are up for discussion and we can reformat after that

* style: formatting tests to added rust fmt

* style: formatting code to match rustfmt

- this resulted mainly in an improved organization of imports

* test: util puff functions and noted input requirements

* test: marking tests bpf where needed